TracePoint の再帰チェックが悪さをして c_call のハンドラ内で throw が発生してフ
ックの実行が飛ばされてしまうことがある不具合を修正しています。発生シナリオは複
雑なのでチケット参照。 [ruby-dev:48290] [Bug #9940]
