Enumerator::Lazy#drop_while でも同様にカウンタの扱いを修正してネストした呼び出
しの時の不具合を修正しています。 [ruby-core:51430] [Bug #7696]
[ruby-core:51420] [Bug #7691]
