Ruby VM による末尾呼び出し最適化を有効にした時に return 文の引数のメソッド内で
発生した例外が正しく rescue できないことがある不具合を修正しています。
[ruby-core:73871] [Bug #12082]
