トップレベルの self(main という特別なオブジェクト)の using がモジュール定義やメ
ソッド定義の中から(send を使って)呼び出された時に ArgumentError を発生させるよ
うにしています。イレギュラーな使い途を潰していってるみたいですね。
