Object#hash によるハッシュ値を Hash で利用する時に相互参照しているオブジェクト
がお互いの hash メソッドの戻り値を元にハッシュ値を計算しようとすると無限再帰に
陥る現象があったので、hash メソッドの呼び出し時に再帰を検出してエラーを起こすよ
うにしています。 [ruby-core:58567] [Bug #9151]
