Method#to_proc で作った Proc オブジェクトにブロックを渡して call すると、次にブ
ロックを渡さずに call してもまだ block_given? が真になったままになる不具合につ
いてのテストを追加しています。これは修正に先んじてテストを追加していたみたいで
す。 [ruby-core:54626] [Bug #8341]
