lambda の無限再起でマシンスタックのオーバフローを起こすテストで子プロセスでオー
バフローを起こさせているのですが、なぜかこれが子プロセス内で捕捉されなくて親プ
ロセスに伝播することがあるらしくて、とりあえず rescue して無視するようにしてい
るそうです。
先の r44123 で捕捉できないっていうのもこの原因不明の現象のことっぽいですね。
