test/test_open3.rb で IO#closed? でチェックしてから IO#close を呼んでるところが
あったので、もう close 済みでも IO#close で IOError が発生しなくなっているので
チェックを削っています。
